AllCops:
  NewCops: enable
  SuggestExtensions: false
  TargetRubyVersion: 3.0

Style/StringLiterals:
  EnforcedStyle: single_quotes

Style/StringLiteralsInInterpolation:
  EnforcedStyle: single_quotes
